services:
  postgres-db:
    image: postgres:16-alpine
    container_name: financial_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-motor_financeiro}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
