spring.application.name=motor-financeiro
spring.cache.type=simple
server.port=8080
logging.level.root=INFO
logging.level.com.motorfinanceiro=DEBUG
fii.health-check.test-ticker=MXRF11

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:motor_financeiro}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:troque_esta_senha}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.ai.google.genai.api-key=${GEMINI_API_KEY}
